### ISSUE TITLE
Right to left

### ISSUE THREAD

**Issue by acaliaro** [Tommigun1980/Xamarin.Forms.DragView#1]
Hi
Is it possible to drag from right to left like on this discussion:

https://forums.xamarin.com/discussion/180729/slide-menu

**Comment by Tommigun1980** [comment]
Hi!

No I left out horizontal dragging until someone requested it. I will implement it for you.

**Comment by Tommigun1980** [comment]
> Hi
> Is it possible to drag from right to left like on this discussion:
> 
> https://forums.xamarin.com/discussion/180729/slide-menu

Version 1.0.0 now has support for arbitrary directions. Please see the documentation at https://github.com/Tommigun1980/Xamarin.Forms.DragView for more info.
